# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: Build
    jobs:
      - job: Frontend
        steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node.js'
        - script: 
            dir;
            npm install -g @angular/cli
            npm install
            ng build --pru
        displayName: 'npm install and build'
  - stage: deployAcceptance
    displayName: Deploy Acceptance
    dependsOn:
    - Build
    jobs:
      - deployment: VMDeploy_Acceptance
        displayName: deploy Acceptance
        environment:
          name: azureenv
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - task: Bash@3
                  displayName: Frontend deploy
                  inputs:
                    targetType: 'inline'
                    script: |
                        mv -v $(Pipeline.Workspace)/frontend/* ./dist
                    workingDirectory: 'C:\inetpub\wwwfrontend'