export interface SeguimientoDiario {
        seguimientoDiarioId?: number,
        contratacionProyectoId?: number,
        observacionSupervisorId?: number,
        fechaSeguimiento?: Date,
        disponibilidadPersonal?: boolean,
        disponibilidadPersonalObservaciones?: string,
        cantidadPersonalProgramado?: number,
        cantidadPersonalTrabajando?: number,
        seGeneroRetrasoPersonal?: boolean,
        numeroHorasRetrasoPersonal?: number,
        disponibilidadMaterialCodigo?: string,
        disponibilidadMaterialObservaciones?: string,
        causaIndisponibilidadMaterialCodigo?: string,
        seGeneroRetrasoMaterial?: boolean,
        numeroHorasRetrasoMaterial?: number,
        disponibilidadEquipoCodigo?: string,
        disponibilidadEquipoObservaciones?: string,
        causaIndisponibilidadEquipoCodigo?: string,
        seGeneroRetrasoEquipo?: boolean,
        numeroHorasRetrasoEquipo?: number,
        productividadCodigo?: string,
        productividadObservaciones?: string,
        causaIndisponibilidadProductividadCodigo?: string,
        seGeneroRetrasoProductividad?: boolean,
        numeroHorasRetrasoProductividad?: number,
        estadoCodigo?: string,
        tieneObservacionApoyo?: boolean,
        tieneObservacionSupervisor?: boolean,
        eliminado?: boolean,
        registroCompleto?: boolean,
        fechaCreacion?: Date,
        usuarioCreacion?: string,
        fechaModificacion?: Date,
        usuarioModificacion?: string,

        seguimientoDiarioObservaciones?: SeguimientoDiarioObservaciones[],
        observacionApoyo?: SeguimientoDiarioObservaciones,
        observacionSupervisor?: SeguimientoDiarioObservaciones,
        observacionDevolucion?: SeguimientoDiarioObservaciones,
        productividadNombre?: string,
        disponibilidadMaterialNombre?: string,
        disponibilidadEquipoNombre?: string,
        causaBajaDisponibilidadMaterialNombre?: string,
        causaBajaDisponibilidadEquipoNombre?: string,
        causaBajaDisponibilidadProductividadNombre?: string,
        
}

export interface SeguimientoDiarioObservaciones{
        seguimientoDiarioObservacionesId?: number,
        seguimientoDiarioId?: number,
        observaciones?: string,
        esSupervision?: boolean,
        fechaCreacion?: Date,
        usuarioCreacion?: string,
        fechaModificacion?: Date,
        usuarioModificacion?: string,
        eliminado?: boolean,
        archivado?: boolean,
}