
namespace asivamosffie.services.Helpers.Enumerator
{
    public enum enumeratorTemplate
    {
        RecuperarClave = 2,
        DisponibilidadPresupuestalGenerada = 4,
        MsjSupervisorGestionPoliza = 5,
        MsjFiduciariaJuridicaGestionPoliza = 6,
        MsjInterventorGestionPoliza = 7,
        MsjSupervisorJuridicaGestionPoliza = 8,
        SolicitarApertura = 10,
        proyectoadministrativocreado = 12,
        ActaInicioFase2ObraInterventoria = 13,
        MsjCoordinadorFuentes = 14,
        MsjEnviarSolicitudContratacion = 15,
        ActividadesNoMonitoreadasProcesoSeleccion = 16,
        Dias2ObraOInterventoriaDocNoCargado=17,
        ConvocarSesionComite = 19,
        OrdenDia = 20,
        NotificacionActaAprobacion = 21,
        EnviarComiteAprobacion = 24,
        ddpSolicitudCreada = 25,

        TablaAprobacionParticipanteActa = 27,
        RegistrosTablaAprobacionParticipanteActa = 28,
      	NotificarFiduciaria322 = 29,
        DDPDevolucion=30,
        DDPRechazado=31, 
        NotificacionContratacion341 = 32,
        DRPNotificacion = 33,
        DDPCancelado = 34,
        DRPCancelado = 35,
        AlertaParticipacionJuridica4_2_1=52,
        AprobarInicio316 = 36,
        AprobarPoliza4diasNoGestion = 37,
        EnviarSupervisor317 = 38, 
        AlertaSupervisor317_2dias = 39, 
        AlertaPolizas317_4dias = 40,
        Alertas2DiasObraInterventoria318 = 41,
        ConActaSinDocumento319 = 43, 
        VerificacionRequisitosTecnicosConstruccionFase2=44,
        EnviarActaParaFirmar319 = 45,

        AlertaJuridicaDerivadaCumplida4_4_1= 51	,
        EnviarActaCargada319 = 46,
        Notificarinterventor=48,
        ObservacionesActaInicioFase2=50,
        NotificacionCompromisos=53,
        msjAprobacion4_1_10 = 54,
        Alerta5Dias4_1_10 = 55,
        NotificacionInconsistencias = 56,
        NotificacionAprobacion = 59,
    }
}